import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react';
import { Navigation, Services, Portfolio, Button, Footer } from './components/index';

export default function Home() {

  const [darkMode, setDarkMode] = useState(true)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>VaniaSavosko Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 transition-all'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='font-burtons text-xl dark:text-teal-600'>portfolio</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl dark:text-teal-600 hover:text-teal-600 dark:hover:text-gray-400' onClick={() => setDarkMode(!darkMode)} /></li>
              <li className='ml-8'><Button value='Resume' href='https://rabota.ua/ua/my/resumes/21419547' /></li>
            </ul>
          </nav>
          <Navigation />
        </section>
        <Services />
        <Portfolio />
      </main>
      <footer className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 transition-all'>
        <Footer />
      </footer>
    </div>
  )
}
